name: gcloud auth and yarn run & install 
on: push

jobs:
    test:
        environment: testing
        env:
            GCP_PROJECT_ID: ${{ secrets.MONGODB_USERNAME }}
            GCP_CREDENTIALS_JSON: ${{ secrets.MONGODB_PASSWORD }}
            PORT: 8080
        runs-on: ubuntu-latest
        steps:
         - name: get the code
           uses: actions/checkout@v3
         - name: Install node js
           uses: actions/setup-node@v3
         - name: Install Yarn
           run: npm install -g yarn
         - name: install dependencies
           run: npm ci
         - name: Authenticate with Google Cloud
           uses: google-github-actions/auth@v2
           with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}